"""
End-to-end driver: loads a test image, runs DCT compression at several
quality settings, writes all figures used by the report and the slide deck.
"""

from __future__ import annotations

import os
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from scipy.datasets import ascent

from dct_compression import (
    BLOCK,
    JPEG_LUMA_Q50,
    T,
    build_dct_matrix,
    compress,
    compression_ratio,
    dct2,
    estimate_bpp,
    idct2,
    mse,
    psnr,
    quality_to_matrix,
)


OUT = Path(__file__).resolve().parent.parent / "outputs"
OUT.mkdir(parents=True, exist_ok=True)


def save(fig, name: str) -> None:
    path = OUT / name
    fig.savefig(path, dpi=140, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {path.name}")


def plot_dct_basis() -> None:
    """Visualize the 64 basis images generated by the 2D DCT-II."""
    fig, axes = plt.subplots(BLOCK, BLOCK, figsize=(6.4, 6.4))
    for u in range(BLOCK):
        for v in range(BLOCK):
            impulse = np.zeros((BLOCK, BLOCK))
            impulse[u, v] = 1.0
            basis = idct2(impulse)
            ax = axes[u, v]
            ax.imshow(basis, cmap="gray", vmin=-0.5, vmax=0.5)
            ax.set_xticks([])
            ax.set_yticks([])
    fig.suptitle("8x8 2D DCT basis images  (u: row, v: column)", y=0.92)
    save(fig, "fig_dct_basis.png")


def plot_quantization_matrices() -> None:
    fig, axes = plt.subplots(1, 3, figsize=(11, 3.5))
    for ax, q in zip(axes, (10, 50, 90)):
        Q = quality_to_matrix(q)
        im = ax.imshow(Q, cmap="viridis")
        ax.set_title(f"Quantization matrix at Q={q}")
        for i in range(BLOCK):
            for j in range(BLOCK):
                ax.text(j, i, f"{int(Q[i, j])}",
                        ha="center", va="center",
                        color="white" if Q[i, j] < Q.max() * 0.6 else "black",
                        fontsize=7)
        ax.set_xticks([])
        ax.set_yticks([])
        fig.colorbar(im, ax=ax, fraction=0.045)
    fig.suptitle("Lower quality -> larger divisors -> coarser coefficients")
    fig.tight_layout()
    save(fig, "fig_quantization_matrices.png")


def plot_block_pipeline(img: np.ndarray, quality: int = 30) -> None:
    """Walk through one 8x8 block, showing DCT -> quantize -> IDCT."""
    by, bx = 200, 200
    block = img[by:by + BLOCK, bx:bx + BLOCK].astype(np.float64)
    shifted = block - 128.0
    F = dct2(shifted)
    Q = quality_to_matrix(quality)
    Fq = np.round(F / Q)
    Fdq = Fq * Q
    recon = np.clip(idct2(Fdq) + 128.0, 0, 255)

    fig, axes = plt.subplots(1, 4, figsize=(12, 3.2))
    panels = [
        ("Spatial block f(x,y)", block, "gray", dict(vmin=0, vmax=255)),
        ("DCT coefficients F(u,v)", np.log1p(np.abs(F)), "magma", {}),
        (f"Quantized F_q (Q={quality})", Fq, "coolwarm",
         dict(vmin=-np.max(np.abs(Fq)) - 1, vmax=np.max(np.abs(Fq)) + 1)),
        ("Reconstructed block", recon, "gray", dict(vmin=0, vmax=255)),
    ]
    for ax, (title, data, cmap, kwargs) in zip(axes, panels):
        im = ax.imshow(data, cmap=cmap, **kwargs)
        ax.set_title(title, fontsize=10)
        for i in range(BLOCK):
            for j in range(BLOCK):
                ax.text(j, i, f"{data[i, j]:.0f}",
                        ha="center", va="center",
                        fontsize=6,
                        color="white" if cmap in ("magma",) else "black")
        ax.set_xticks([])
        ax.set_yticks([])
    fig.suptitle(f"One 8x8 block through the JPEG baseline pipeline (block origin {by},{bx})")
    fig.tight_layout()
    save(fig, "fig_block_pipeline.png")
    nonzero_before = int(np.count_nonzero(np.round(F)))
    nonzero_after = int(np.count_nonzero(Fq))
    return dict(
        nonzero_before_quant=nonzero_before,
        nonzero_after_quant=nonzero_after,
        block_psnr=psnr(block, recon),
    )


def plot_reconstruction_grid(img: np.ndarray, qualities) -> list:
    rows = []
    n = len(qualities) + 1
    fig, axes = plt.subplots(1, n, figsize=(3 * n, 3.4))
    axes[0].imshow(img, cmap="gray", vmin=0, vmax=255)
    axes[0].set_title("Original")
    axes[0].set_xticks([])
    axes[0].set_yticks([])
    for ax, q in zip(axes[1:], qualities):
        r = compress(img, quality=q)
        ax.imshow(r["reconstructed"], cmap="gray", vmin=0, vmax=255)
        p = psnr(r["original"], r["reconstructed"])
        bpp = estimate_bpp(r["quantized"])
        cr = compression_ratio(r["quantized"])
        ax.set_title(f"Q={q}\nPSNR={p:.2f} dB\nCR={cr:.2f}x")
        ax.set_xticks([])
        ax.set_yticks([])
        rows.append(dict(
            quality=q,
            psnr_db=p,
            mse=mse(r["original"], r["reconstructed"]),
            sparsity=r["sparsity"],
            bpp=bpp,
            compression_ratio=cr,
        ))
    fig.suptitle("Reconstruction quality vs. quality factor")
    fig.tight_layout()
    save(fig, "fig_reconstruction_grid.png")
    return rows


def plot_rate_distortion(rows: list) -> None:
    qs = [r["quality"] for r in rows]
    psnrs = [r["psnr_db"] for r in rows]
    crs = [r["compression_ratio"] for r in rows]
    bpps = [r["bpp"] for r in rows]

    fig, ax1 = plt.subplots(figsize=(7.5, 4.2))
    ax1.plot(qs, psnrs, "o-", color="#1f77b4", label="PSNR (dB)")
    ax1.set_xlabel("Quality factor Q")
    ax1.set_ylabel("PSNR (dB)", color="#1f77b4")
    ax1.tick_params(axis="y", labelcolor="#1f77b4")
    ax1.grid(True, linestyle=":", alpha=0.5)

    ax2 = ax1.twinx()
    ax2.plot(qs, crs, "s--", color="#d62728", label="Compression ratio")
    ax2.set_ylabel("Compression ratio (8 bpp / est. bpp)", color="#d62728")
    ax2.tick_params(axis="y", labelcolor="#d62728")

    ax1.set_title("Rate-distortion trade-off")
    fig.tight_layout()
    save(fig, "fig_rate_distortion.png")

    fig2, ax = plt.subplots(figsize=(7.5, 4.2))
    ax.plot(bpps, psnrs, "o-", color="#2ca02c")
    ax.set_xlabel("Estimated bits per pixel (entropy)")
    ax.set_ylabel("PSNR (dB)")
    ax.set_title("PSNR vs. bit-rate")
    ax.grid(True, linestyle=":", alpha=0.5)
    for q, x, y in zip(qs, bpps, psnrs):
        ax.annotate(f"Q={q}", (x, y), textcoords="offset points",
                    xytext=(6, 4), fontsize=8)
    save(fig2, "fig_bpp_vs_psnr.png")


def plot_error_map(img: np.ndarray, q: int = 20) -> None:
    r = compress(img, quality=q)
    err = r["original"] - r["reconstructed"]
    fig, axes = plt.subplots(1, 3, figsize=(12, 3.8))
    axes[0].imshow(r["original"], cmap="gray", vmin=0, vmax=255)
    axes[0].set_title("Original")
    axes[1].imshow(r["reconstructed"], cmap="gray", vmin=0, vmax=255)
    axes[1].set_title(f"Reconstruction (Q={q})")
    amp = float(np.max(np.abs(err)))
    im = axes[2].imshow(err, cmap="coolwarm", vmin=-amp, vmax=amp)
    axes[2].set_title("Error map (original - reconstructed)")
    for ax in axes:
        ax.set_xticks([])
        ax.set_yticks([])
    fig.colorbar(im, ax=axes[2], fraction=0.045)
    fig.tight_layout()
    save(fig, "fig_error_map.png")


def plot_coefficient_histogram(img: np.ndarray) -> None:
    r = compress(img, quality=50)
    fig, axes = plt.subplots(1, 2, figsize=(10, 3.6))
    axes[0].hist(r["dct_blocks"].ravel(), bins=80, color="#1f77b4")
    axes[0].set_yscale("log")
    axes[0].set_title("Raw DCT coefficient distribution (log)")
    axes[0].set_xlabel("coefficient value")

    axes[1].hist(r["quantized"].ravel(), bins=np.arange(-30, 31) - 0.5,
                 color="#d62728")
    axes[1].set_yscale("log")
    axes[1].set_title(f"Quantized (sparsity = {r['sparsity']*100:.1f}% zeros)")
    axes[1].set_xlabel("quantized coefficient")
    fig.tight_layout()
    save(fig, "fig_coeff_histograms.png")


def main():
    print("Loading test image ...")
    img = ascent().astype(np.float64)
    print(f"  shape={img.shape}, min={img.min():.0f}, max={img.max():.0f}")

    print("Generating figures ...")
    plot_dct_basis()
    plot_quantization_matrices()
    block_stats = plot_block_pipeline(img, quality=30)
    rows = plot_reconstruction_grid(img, qualities=[90, 50, 20, 10])
    plot_rate_distortion(rows)
    plot_error_map(img, q=20)
    plot_coefficient_histogram(img)

    print("\nSummary table:")
    print(f"  {'Q':>3} {'PSNR (dB)':>10} {'MSE':>8} {'Sparsity':>9} {'bpp':>6} {'CR':>6}")
    for r in rows:
        print(f"  {r['quality']:>3} {r['psnr_db']:>10.2f} "
              f"{r['mse']:>8.2f} {r['sparsity']*100:>8.1f}% "
              f"{r['bpp']:>6.2f} {r['compression_ratio']:>6.2f}x")

    print("\nBlock-pipeline diagnostics:")
    for k, v in block_stats.items():
        print(f"  {k}: {v}")

    with open(OUT / "metrics.csv", "w") as f:
        f.write("quality,psnr_db,mse,sparsity,bpp,compression_ratio\n")
        for r in rows:
            f.write(f"{r['quality']},{r['psnr_db']:.4f},{r['mse']:.4f},"
                    f"{r['sparsity']:.4f},{r['bpp']:.4f},"
                    f"{r['compression_ratio']:.4f}\n")
    print(f"  wrote {OUT / 'metrics.csv'}")

    return rows, block_stats


if __name__ == "__main__":
    main()
